### ISSUE TITLE
[FE] 공통 컴포넌트 작업

### ISSUE THREAD

**Issue by jjaeho0415** [OZ-Coding-School/oz_02_main-003-FE#8]
## Description
페이지 개발에 필요한 공통 컴포넌트 제작 작업

## To-do
- [ ] 길쭉한 버튼(로그인 버튼 제외)
- [ ] 재료 관련 버튼(삭제, 추가 등)
- [ ] 모달
- [ ] 작은 동그라미 버튼
